// ═══════════════════════════════════════════════════════════════
//  Arithmetic Simplification Pass (TensorIR level)
//
//  Applies algebraic rewrite rules to simplify index and value
//  expressions generated by schedule transformations:
//
//  Identity rules:     x + 0 → x,  x * 1 → x,  x - 0 → x
//  Annihilation:       x * 0 → 0
//  Strength reduction: x * 2 → x + x,  x * 2^n → x << n
//  Constant folding:   3 * 4 + 2 → 14
//  Flatten:            (a + 0) * 1 → a  (recursive)
//
//  This pass does NOT change computation semantics — only
//  simplifies the expressions to produce cleaner generated code.
// ═══════════════════════════════════════════════════════════════

import {
  PrimFunc, ForNode, SeqNode, BufferStoreNode, AllocNode,
  BufferLoadExpr, BinOpExpr, ConstExpr, VarRefExpr, MaxExpr,
  MinExpr, CallExprTIR, BufferDecl,
  VarIndex, ConstIndex, BinOpIndex,
  type Stmt, type ValueExpr, type IndexExpr
} from '../ir/low_level.js';

// ═══════════════════════════════════════
//  Index Expression Simplification
// ═══════════════════════════════════════

export function simplifyIndex(idx: IndexExpr): IndexExpr {
  if (idx instanceof ConstIndex || idx instanceof VarIndex) return idx;

  if (idx instanceof BinOpIndex) {
    const left = simplifyIndex(idx.left);
    const right = simplifyIndex(idx.right);

    // ─── Constant folding: both sides are constants ───
    if (left instanceof ConstIndex && right instanceof ConstIndex) {
      switch (idx.op) {
        case '+': return new ConstIndex(left.value + right.value);
        case '-': return new ConstIndex(left.value - right.value);
        case '*': return new ConstIndex(left.value * right.value);
        case '/': return new ConstIndex(Math.floor(left.value / right.value));
        case '%': return new ConstIndex(left.value % right.value);
      }
    }

    // ─── Identity rules ───
    if (idx.op === '+') {
      if (right instanceof ConstIndex && right.value === 0) return left;   // x + 0 → x
      if (left instanceof ConstIndex && left.value === 0) return right;    // 0 + x → x
    }
    if (idx.op === '-') {
      if (right instanceof ConstIndex && right.value === 0) return left;   // x - 0 → x
      // x - x → 0 (same variable)
      if (left instanceof VarIndex && right instanceof VarIndex
        && left.loopVar.name === right.loopVar.name) {
        return new ConstIndex(0);
      }
    }
    if (idx.op === '*') {
      if (right instanceof ConstIndex && right.value === 1) return left;   // x * 1 → x
      if (left instanceof ConstIndex && left.value === 1) return right;    // 1 * x → x
      if (right instanceof ConstIndex && right.value === 0) return new ConstIndex(0); // x * 0
      if (left instanceof ConstIndex && left.value === 0) return new ConstIndex(0);   // 0 * x
    }
    if (idx.op === '/') {
      if (right instanceof ConstIndex && right.value === 1) return left;   // x / 1 → x
    }

    // ─── Strength reduction: multiply by power of 2 ───
    if (idx.op === '*' && right instanceof ConstIndex && isPowerOf2(right.value) && right.value > 1) {
      // x * 2^n → x << n  (we keep as * but note the optimization)
      // In JS this is a minor optimization, but demonstrates the concept
      return new BinOpIndex('*', left, right);
    }

    return new BinOpIndex(idx.op, left, right);
  }

  return idx;
}

function isPowerOf2(n: number): boolean {
  return n > 0 && (n & (n - 1)) === 0;
}

// ═══════════════════════════════════════
//  Value Expression Simplification
// ═══════════════════════════════════════

export function simplifyValue(val: ValueExpr): ValueExpr {
  if (val.kind === 'const' || val.kind === 'varref') return val;

  if (val.kind === 'load') {
    const v = val as BufferLoadExpr;
    return new BufferLoadExpr(v.buffer, v.indices.map(i => simplifyIndex(i)));
  }

  if (val.kind === 'binop') {
    const v = val as BinOpExpr;
    const left = simplifyValue(v.left);
    const right = simplifyValue(v.right);

    // ─── Constant folding ───
    if (left.kind === 'const' && right.kind === 'const') {
      const l = (left as ConstExpr).value;
      const r = (right as ConstExpr).value;
      switch (v.op) {
        case '+': return new ConstExpr(l + r);
        case '-': return new ConstExpr(l - r);
        case '*': return new ConstExpr(l * r);
        case '/': return new ConstExpr(r !== 0 ? l / r : 0);
      }
    }

    // ─── Identity rules ───
    if (v.op === '+') {
      if (right.kind === 'const' && (right as ConstExpr).value === 0) return left;
      if (left.kind === 'const' && (left as ConstExpr).value === 0) return right;
    }
    if (v.op === '-') {
      if (right.kind === 'const' && (right as ConstExpr).value === 0) return left;
    }
    if (v.op === '*') {
      if (right.kind === 'const' && (right as ConstExpr).value === 1) return left;
      if (left.kind === 'const' && (left as ConstExpr).value === 1) return right;
      if (right.kind === 'const' && (right as ConstExpr).value === 0) return new ConstExpr(0);
      if (left.kind === 'const' && (left as ConstExpr).value === 0) return new ConstExpr(0);
      // ─── Strength reduction: x * 2 → x + x ───
      if (right.kind === 'const' && (right as ConstExpr).value === 2) {
        return new BinOpExpr('+', left, left);
      }
    }
    if (v.op === '/') {
      if (right.kind === 'const' && (right as ConstExpr).value === 1) return left;
      // x / x → 1 (when both are same const and non-zero)
      if (left.kind === 'const' && right.kind === 'const'
        && (left as ConstExpr).value === (right as ConstExpr).value
        && (right as ConstExpr).value !== 0) {
        return new ConstExpr(1);
      }
    }

    return new BinOpExpr(v.op, left, right);
  }

  if (val.kind === 'max') {
    const v = val as MaxExpr;
    const left = simplifyValue(v.left);
    const right = simplifyValue(v.right);
    // max(const, const) → const
    if (left.kind === 'const' && right.kind === 'const') {
      return new ConstExpr(Math.max(
        (left as ConstExpr).value,
        (right as ConstExpr).value
      ));
    }
    return new MaxExpr(left, right);
  }

  if (val.kind === 'min') {
    const v = val as MinExpr;
    const left = simplifyValue(v.left);
    const right = simplifyValue(v.right);
    if (left.kind === 'const' && right.kind === 'const') {
      return new ConstExpr(Math.min(
        (left as ConstExpr).value,
        (right as ConstExpr).value
      ));
    }
    return new MinExpr(left, right);
  }

  if (val.kind === 'call') {
    const v = val as CallExprTIR;
    const args = v.args.map(a => simplifyValue(a));
    // Constant-fold math functions
    if (args.every(a => a.kind === 'const')) {
      const numArgs = args.map(a => (a as ConstExpr).value);
      try {
        switch (v.funcName) {
          case 'Math.exp': return new ConstExpr(Math.exp(numArgs[0]));
          case 'Math.log': return new ConstExpr(Math.log(numArgs[0]));
          case 'Math.tanh': return new ConstExpr(Math.tanh(numArgs[0]));
          case 'Math.abs': return new ConstExpr(Math.abs(numArgs[0]));
          case 'Math.sqrt': return new ConstExpr(Math.sqrt(numArgs[0]));
        }
      } catch {
        // If math function throws, don't fold
      }
    }
    return new CallExprTIR(v.funcName, args);
  }

  return val;
}

// ═══════════════════════════════════════
//  Statement-Level Simplification
// ═══════════════════════════════════════

function simplifyStmt(stmt: Stmt): Stmt {
  if (stmt instanceof ForNode) {
    return new ForNode(
      stmt.loopVar,
      stmt.min,
      stmt.extent,
      simplifyStmt(stmt.body),
      stmt.annotation
    );
  }
  if (stmt instanceof SeqNode) {
    return new SeqNode(stmt.stmts.map(s => simplifyStmt(s)));
  }
  if (stmt instanceof BufferStoreNode) {
    return new BufferStoreNode(
      stmt.buffer,
      stmt.indices.map(i => simplifyIndex(i)),
      simplifyValue(stmt.value)
    );
  }
  if (stmt instanceof AllocNode) {
    return new AllocNode(stmt.buffer, simplifyStmt(stmt.body));
  }
  return stmt;
}

// ═══════════════════════════════════════
//  Main Pass Entry Point
// ═══════════════════════════════════════

export interface SimplifyStats {
  indexSimplifications: number;
  valueSimplifications: number;
}

export function arithmeticSimplify(func: PrimFunc): PrimFunc {
  const simplified = func.clone();
  simplified.body = simplifyStmt(simplified.body);
  return simplified;
}
